### ISSUE TITLE
meson project script missing

### ISSUE THREAD

**Issue by Pertekm** [matveyt/shebang#1]
Can not find a meson project script (meson.build) file.
How to compile shebang with meson?

**Comment by Pertekm** [comment]
Found the file, it was deleted by commit https://github.com/matveyt/shebang/commit/791e437aa95177f705d09da24012e71e34ef3061
why?

**Comment by Pertekm** [comment]
I used the deleted meson.build file and could compile shebang.

But i do not know how to use shebang in my case:
I have a script file (named "foreman" in a bin folder) with the content
`#!/bin/bash -i
bin/update
bundle exec foreman start -f Procfile`
i would like to execute this script by command "foreman". currently i need to use the command "bash foreman" to execute it under windows.
How to execute it with help of shebang?

**Comment by matveyt** [comment]
I dropped meson.build, because I don't use it anymore. Also it does not do much here. You can compile simply in the command line, e.g.: `gcc -s shebang.c -o shebang -lshlwapi` as noted in README.

To use shebang make a symlink (like `mklink foreman.exe shebang.exe` note: usually needs administrative access), or rename, or copy. For convenience, put the symlink on Windows PATH (no matter which directory).

**Comment by matveyt** [comment]
meson.build is back. Closing the issue.
